name: Contracts Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]


jobs:
  build:
    name: Formatting, Tests, and Static Analysis
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Check formatting
        run: forge fmt --check

      - name: Run tests
        env:
          HOLESKY_RPC_URL: https://eth-holesky.g.alchemy.com/v2/${{ secrets.ALCHEMY_API_KEY }}
          SEPOLIA_RPC_URL: https://eth-sepolia.g.alchemy.com/v2/${{ secrets.ALCHEMY_API_KEY }}
          MAINNET_RPC_URL: https://eth-mainnet.g.alchemy.com/v2/${{ secrets.ALCHEMY_API_KEY }}
          CHAIN_ID: 1
        run: forge test --via-ir

      - name: Run static analysis
        uses: crytic/slither-action@v0.4.0
        id: slither
        with:
          target: .
          fail-on: none
        